--- 
knit: "bookdown::render_book"
title: "Source code for _High elevation Himalayan birds shift elevations to track thermal regimes across seasons_"
author:
    - Sahas Barve
    - Tarun Menon
    - Vijay Ramesh
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    fig_caption: yes
  bookdown::pdf_document2:
    documentclass: scrreprt
    toc-depth: 1
    secnumdepth: 2
    geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
biblio-style: apalike
link-citations: yes
github-repo: vjjan91/elevMigration
---

# Introduction

This is the readable version containing analysis that models the extent of elevational migration in Himalayan birds using community science data (eBird).   

## Data processing

The data processing for this project is described in the following sections. Navigate through them using the links in the sidebar.

## Attribution

Please contact the following in case of interest in the project.

- Vijay Ramesh (repo maintainer)
    - PhD student, Columbia University

## Data access

The data used in this work is archived on Zenodo.  
---

![**Spatially thinned checklist locations of bird observations across the Himalayas.**
Map showing sampling points included in our dataset for elevational migration in Himalayan birds. For ease of visualization, we spatially thinned localities to show only 710 unique locations, by ensuring a minimum distance of fifteen kilometres between each checklist locality. This process was carried using the thin function from the spThin package within the R programming environment (Aiello-Lammens et al., 2019; R Core Team, 2021). This map was created in ArcGIS Pro with a shaded relief from a high-resolution digital elevation model (SRTM).](figs/fig01.png)